// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_YaWu7Vs_9QQvtpk0ZvBGrZeDSzeZvE',
    appId: '1:506154778945:web:bdb423e9679204ba8fe1c0',
    messagingSenderId: '506154778945',
    projectId: 'pacelli-35621',
    authDomain: 'pacelli-35621.firebaseapp.com',
    storageBucket: 'pacelli-35621.firebasestorage.app',
    measurementId: 'G-WQCHWQHHMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NQssyQ7pK0qylIJkzBl9gxbGgGO7dqA',
    appId: '1:506154778945:android:ba0477f9d6bd70278fe1c0',
    messagingSenderId: '506154778945',
    projectId: 'pacelli-35621',
    storageBucket: 'pacelli-35621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrhzTC8DzT4yMkdAkrhsQY3qARlmMH0FE',
    appId: '1:506154778945:ios:24104e64f29dc4ff8fe1c0',
    messagingSenderId: '506154778945',
    projectId: 'pacelli-35621',
    storageBucket: 'pacelli-35621.firebasestorage.app',
    iosClientId: '506154778945-68ta2sjllehr81l6ubl34e8htfcgtfig.apps.googleusercontent.com',
    iosBundleId: 'com.pacelli.pacelli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrhzTC8DzT4yMkdAkrhsQY3qARlmMH0FE',
    appId: '1:506154778945:ios:24104e64f29dc4ff8fe1c0',
    messagingSenderId: '506154778945',
    projectId: 'pacelli-35621',
    storageBucket: 'pacelli-35621.firebasestorage.app',
    iosClientId: '506154778945-68ta2sjllehr81l6ubl34e8htfcgtfig.apps.googleusercontent.com',
    iosBundleId: 'com.pacelli.pacelli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn_YaWu7Vs_9QQvtpk0ZvBGrZeDSzeZvE',
    appId: '1:506154778945:web:1da61ce6f85fa4ed8fe1c0',
    messagingSenderId: '506154778945',
    projectId: 'pacelli-35621',
    authDomain: 'pacelli-35621.firebaseapp.com',
    storageBucket: 'pacelli-35621.firebasestorage.app',
    measurementId: 'G-44CF8WP5XV',
  );
}
